require("dotenv").config();
const mongoose = require("mongoose");
// Import the model
const Property = require("../models/Property");

// Place the array you want to seed
const propertiesToSeed = [
  {
    title: "Parking David",
    description: "Secure parking space in a great location.",
    owner: "64367e20c9b3919e623f083e",
    category: "parking",
    price: 100,
    size: 15,
    address: "Carrer de Balmes 1",
    city: "Barcelona",
    images: [
      "https://img3.idealista.com/blur/WEB_LISTING-M/0/id.pro.es.image.master/a1/16/21/1098526716.jpg",
      "https://st3.idealista.com/news/archivos/styles/fullwidth_xl_2x/public/2016-06/garaje.jpg?VersionId=8aca5Crf6yyOuOGvK1IFsny2KFW7egr1&itok=oemK7j9y",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTVY5jwhPEIIY6VcDEQSyjTRkQPAAuVAtnOMbDcvvy_eY4nntpJrWIv1a9mB7pr_D24VSg&usqp=CAU",
    ],
    country: "Spain",
    zipCode: "08007",
    summary: "Secure parking space in a great location.",
    coordinates: { lat: 41.387015, lng: 2.170047 },
    amenities: ["wifi", "tv"],
    active: true,
  },
  {
    title: "Parking Claris",
    description: "Convenient parking space in the city center.",
    owner: "643682134e3380f7d851a50f",
    images: [
      "https://static.inmofactory.com/images/inmofactory/documents/1/113416/31295208/494938156.jpg?rule=original",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTVY5jwhPEIIY6VcDEQSyjTRkQPAAuVAtnOMbDcvvy_eY4nntpJrWIv1a9mB7pr_D24VSg&usqp=CAU",
    ],
    category: "parking",
    price: 120,
    size: 16,
    address: "Carrer de Pau Claris 2",
    city: "Barcelona",
    country: "Spain",
    zipCode: "08010",
    summary: "Convenient parking space in the city center.",
    coordinates: { lat: 41.389497, lng: 2.17528 },
    amenities: ["wifi", "tv"],
    active: true,
  },
  {
    title: "Parking Llúria",
    description: "Spacious parking space near popular attractions.",
    owner: "6437ef04d35e3202ffcb577e",
    images: [
      "https://img3.idealista.com/blur/WEB_LISTING-M/0/id.pro.es.image.master/e2/42/ed/903440669.jpg",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTVY5jwhPEIIY6VcDEQSyjTRkQPAAuVAtnOMbDcvvy_eY4nntpJrWIv1a9mB7pr_D24VSg&usqp=CAU",
    ],
    category: "parking",
    price: 140,
    size: 18,
    address: "Carrer de Roger de Llúria 3",
    city: "Barcelona",
    country: "Spain",
    zipCode: "08009",
    summary: "Spacious parking space near popular attractions.",
    coordinates: { lat: 41.392341, lng: 2.172927 },
    amenities: ["wifi", "tv"],
    active: true,
  },
  {
    title: "Parking Girona",
    description: "Underground parking space close to public transport.",
    owner: "643816e5bac40f86d90085bd",
    images: [
      "https://img3.idealista.com/blur/WEB_DETAIL_TOP-L-L/0/id.pro.es.image.master/c3/3b/de/807963436.jpg",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTVY5jwhPEIIY6VcDEQSyjTRkQPAAuVAtnOMbDcvvy_eY4nntpJrWIv1a9mB7pr_D24VSg&usqp=CAU",
    ],
    category: "parking",
    price: 150,
    size: 20,
    address: "Carrer de Girona 4",
    city: "Barcelona",
    country: "Spain",
    zipCode: "08010",
    summary: "Underground parking space close to public transport.",
    coordinates: { lat: 41.394427, lng: 2.169796 },
    amenities: ["wifi", "tv"],
    active: true,
  },
  {
    title: "Parking Bailén",
    description: "Centrally located parking space with easy access.",
    owner: "64381929bac40f86d9008606",
    images: [
      "https://st3.idealista.com/news/archivos/styles/fullwidth_xl_2x/public/2016-06/garaje.jpg?VersionId=8aca5Crf6yyOuOGvK1IFsny2KFW7egr1&itok=oemK7j9y",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTVY5jwhPEIIY6VcDEQSyjTRkQPAAuVAtnOMbDcvvy_eY4nntpJrWIv1a9mB7pr_D24VSg&usqp=CAU",
    ],
    category: "parking",
    price: 160,
    size: 22,
    address: "Carrer de Bailèn 5",
    city: "Barcelona",
    country: "Spain",
    zipCode: "08010",
    summary: "Centrally located parking space with easy access.",
    coordinates: { lat: 41.396663, lng: 2.175129 },
    amenities: ["wifi", "tv"],
    active: true,
  },
  {
    title: "Basement Storage",
    description: "Large storage space in a dry basement area.",
    owner: "6439656c74fac438aa77b7a5",
    category: "storage",
    price: 50,
    size: 10,
    address: "Carrer de Casp 1",
    city: "Barcelona",
    images: [
      "https://res.cloudinary.com/duw4zfhmh/image/upload/v1681671527/at_mine/IMG_4653_grsqd8.jpg",
    ],
    country: "Spain",
    zipCode: "08010",
    summary: "Large storage space in a dry basement area.",
    coordinates: { lat: 41.389441, lng: 2.173356 },
    amenities: ["elevator", "washer"],
    active: true,
  },
  {
    title: "Secure Storage Room",
    description: "Safe and secure storage space in a modern building.",
    owner: "643bbce594c0f104626df908",
    category: "storage",
    price: 80,
    size: 12,
    address: "Carrer de Balmes 2",
    city: "Barcelona",
    images: [
      "https://res.cloudinary.com/duw4zfhmh/image/upload/v1681671526/at_mine/IMG_4654_wpudxt.jpg",
    ],
    country: "Spain",
    zipCode: "08007",
    summary: "Safe and secure storage space in a modern building.",
    coordinates: { lat: 41.386629, lng: 2.166195 },
    amenities: ["elevator", "airConditioning"],
    active: true,
  },
  {
    title: "Climate-Controlled Storage",
    description: "Climate-controlled storage space for sensitive items.",
    owner: "64367e20c9b3919e623f083e",
    category: "storage",
    price: 100,
    size: 15,
    address: "Carrer de Mallorca 3",
    city: "Barcelona",
    images: [
      "https://mobileimages.lowes.com/marketingimages/cc73572f-fc86-48ed-8381-3620b69ffe68/DP18-197565-NPC-9-Basement-Storage-Organization-Ideas-AH-v2.jpg",
    ],
    country: "Spain",
    zipCode: "08014",
    summary: "Climate-controlled storage space for sensitive items.",
    coordinates: { lat: 41.382966, lng: 2.154899 },
    amenities: ["airConditioning", "heating"],
    active: true,
  },
  {
    title: "Attic with terrace",
    description:
      "Bright and spacious attic with large terrace and stunning views.",
    owner: "643682134e3380f7d851a50f",
    category: "attic",
    price: 250,
    size: 80,
    images: [
      "https://res.cloudinary.com/duw4zfhmh/image/upload/v1681671527/at_mine/IMG_4652_vupuh3.png",
      "https://res.cloudinary.com/duw4zfhmh/image/upload/v1681671527/at_mine/IMG_4648_hcn4tq.jpg",
    ],
    address: "Carrer de la Marina 145",
    city: "Barcelona",
    country: "Spain",
    zipCode: "08013",
    summary: "Bright and spacious attic with large terrace and stunning views.",
    coordinates: { lat: 41.410941, lng: 2.19782 },
    amenities: [
      "wifi",
      "tv",
      "airConditioning",
      "heating",
      "washer",
      "elevator",
    ],
    active: true,
  },
  {
    title: "Penthouse in Eixample",
    description: "Stylish penthouse with modern design and great location.",
    owner: "6437ef04d35e3202ffcb577e",
    category: "attic",
    price: 350,
    size: 100,
    images: [
      "https://res.cloudinary.com/duw4zfhmh/image/upload/v1681671527/at_mine/IMG_4648_hcn4tq.jpg",
      "https://res.cloudinary.com/duw4zfhmh/image/upload/v1681671527/at_mine/IMG_4649_ekn0w1.jpg",
    ],
    address: "Carrer del Consell de Cent 205",
    city: "Barcelona",
    country: "Spain",
    zipCode: "08011",
    summary: "Stylish penthouse with modern design and great location.",
    coordinates: { lat: 41.384733, lng: 2.159904 },
    amenities: [
      "wifi",
      "music",
      "tv",
      "airConditioning",
      "heating",
      "washer",
      "dryer",
      "dishwasher",
      "elevator",
    ],
    active: true,
  },
  {
    title: "Charming attic in Gracia",
    description:
      "Lovely and cozy attic in the heart of the Gracia neighborhood.",
    owner: "643816e5bac40f86d90085bd",
    category: "attic",
    price: 200,
    size: 60,
    images: [
      "https://res.cloudinary.com/duw4zfhmh/image/upload/v1681671527/at_mine/IMG_4650_stx5ms.jpg",
      "https://res.cloudinary.com/duw4zfhmh/image/upload/v1681671527/at_mine/IMG_4647_ma6dpf.jpg",
    ],
    address: "Carrer de Ontinyent 28",
    city: "Barcelona",
    country: "Spain",
    zipCode: "08012",
    summary: "Lovely and cozy attic in the heart of the Gracia neighborhood.",
    coordinates: { lat: 41.405242, lng: 2.154847 },
    amenities: ["wifi", "tv", "heating"],
    active: true,
  },
  {
    title: "Luxury Villa with Private Pool",
    description:
      "Stunning luxury villa with private pool and amazing views of the sea.",
    owner: "64381929bac40f86d9008606",
    category: "pool",
    price: 800,
    size: 400,
    address: "Carrer de Mallorca 1",
    city: "Barcelona",
    country: "Spain",
    zipCode: "08008",
    summary:
      "Stunning luxury villa with private pool and amazing views of the sea.",
    coordinates: { lat: 41.389087, lng: 2.155411 },
    amenities: [
      "wifi",
      "music",
      "tv",
      "airConditioning",
      "washer",
      "dryer",
      "elevator",
      "petFriendly",
    ],
    images: [
      "https://res.cloudinary.com/duw4zfhmh/image/upload/v1681671528/at_mine/IMG_4638_x7zrze.jpg",
      "https://res.cloudinary.com/duw4zfhmh/image/upload/v1681671528/at_mine/IMG_4636_cdnqha.jpg",
    ],
    active: true,
  },
  {
    title: "Modern Apartment with Pool",
    description:
      "Stylish and modern apartment with a shared pool and great city views.",
    owner: "6439656c74fac438aa77b7a5",
    category: "pool",
    price: 150,
    size: 80,
    address: "Carrer de Valencia 2",
    city: "Barcelona",
    country: "Spain",
    zipCode: "08015",
    summary:
      "Stylish and modern apartment with a shared pool and great city views.",
    coordinates: { lat: 41.383834, lng: 2.154936 },
    amenities: ["wifi", "tv", "airConditioning", "washer", "elevator"],
    images: [
      "https://res.cloudinary.com/duw4zfhmh/image/upload/v1681671528/at_mine/IMG_4637_h6iyrl.jpg",
      "https://res.cloudinary.com/duw4zfhmh/image/upload/v1681671528/at_mine/IMG_4639_jzsdhf.jpg",
      "https://res.cloudinary.com/duw4zfhmh/image/upload/v1681673356/at_mine/Screenshot_2023-04-16_at_21.29.04_vawmyd.png",
    ],
    active: true,
  },
  {
    title: "Confy City Pool Penthouse",
    description: "Stunning villa with a large private pool and scenic views.",
    owner: "643bbce594c0f104626df908",
    category: "pool",
    price: 350,
    size: 400,
    address: "Carrer de la Plana 8",
    city: "Barcelona",
    country: "Spain",
    zipCode: "08034",
    images: [
      "https://res.cloudinary.com/duw4zfhmh/image/upload/v1681672477/at_mine/3fc77a338ce3081140ec98d8846076ee--cool-apartments-holiday-apartments_mtlmqs.jpg",
      "https://res.cloudinary.com/duw4zfhmh/image/upload/v1681672477/at_mine/66_ebrwl2.jpg",
      "https://res.cloudinary.com/duw4zfhmh/image/upload/v1681672478/at_mine/180118_0021b_ohwgzy.jpg",
    ],
    summary: "Stunning villa with a large private pool and scenic views.",
    coordinates: { lat: 41.421889, lng: 2.122167 },
    amenities: [
      "wifi",
      "tv",
      "airConditioning",
      "heating",
      "washer",
      "dryer",
      "dishwasher",
      "petFriendly",
    ],
    active: true,
  },
  {
    title: "Contemporary Pool House",
    description:
      "Modern and stylish pool house with outdoor seating and a BBQ area.",
    owner: "64367e20c9b3919e623f083e",
    category: "pool",
    price: 200,
    size: 100,
    address: "Carrer de l'Avinguda del Paral·lel 6",
    city: "Barcelona",
    country: "Spain",
    zipCode: "08015",
    images: [
      "https://res.cloudinary.com/duw4zfhmh/image/upload/v1681672478/at_mine/180118_0021b_ohwgzy.jpg",
      "https://res.cloudinary.com/duw4zfhmh/image/upload/v1681672478/at_mine/sa-terraza-1_fvvq5a.jpg",
      "https://res.cloudinary.com/duw4zfhmh/image/upload/v1681672477/at_mine/rooftop-pool-barcelona-grandhotelcentral-1_c41ywo.jpg",
    ],
    summary:
      "Modern and stylish pool house with outdoor seating and a BBQ area.",
    coordinates: { lat: 41.375486, lng: 2.162586 },
    amenities: [
      "wifi",
      "tv",
      "airConditioning",
      "heating",
      "washer",
      "dryer",
      "dishwasher",
      "petFriendly",
      "smokingAllowed",
    ],
    active: true,
  },
  {
    title: "Spacious Barbecue Garden",
    description:
      "Large outdoor area perfect for hosting barbecues and gatherings.",
    owner: "64367e20c9b3919e623f083e",
    category: "barbecue",
    price: 200,
    size: 150,
    address: "Carrer de la Diputació 100",
    city: "Barcelona",
    country: "Spain",
    zipCode: "08015",
    summary: "Large outdoor area perfect for hosting barbecues and gatherings.",
    coordinates: { lat: 41.38891, lng: 2.15982 },
    amenities: ["elevator", "petFriendly", "eventFriendly"],
    images: [
      "https://res.cloudinary.com/duw4zfhmh/image/upload/v1681673137/at_mine/313249925_mct4zw.jpg",
    ],
    active: true,
  },
  {
    title: "Luxury Barbecue Area",
    description:
      "Elegant outdoor area with top-of-the-line barbecue equipment.",
    owner: "643682134e3380f7d851a50f",
    category: "barbecue",
    price: 300,
    size: 100,
    address: "Carrer de Sardenya 50",
    city: "Barcelona",
    country: "Spain",
    zipCode: "08005",
    summary: "Elegant outdoor area with top-of-the-line barbecue equipment.",
    coordinates: { lat: 41.40013, lng: 2.18958 },
    amenities: ["airConditioning", "tv", "kidFriendly"],
    images: [
      "https://res.cloudinary.com/duw4zfhmh/image/upload/v1681673482/at_mine/4f65fbbbe2a3133921fd017b0fee25be_mquc3e.jpg",
      "https://res.cloudinary.com/duw4zfhmh/image/upload/v1681673137/at_mine/Rattan-furniture-and-large-bbq-grill_s4lx7r.jpg",
    ],
    active: true,
  },
  {
    title: "Spacious Outdoor Area with BBQ",
    description:
      "Enjoy the Mediterranean climate with this spacious outdoor area featuring a BBQ and seating for 8.",
    owner: "6437ef04d35e3202ffcb577e",
    images: [
      "https://res.cloudinary.com/duw4zfhmh/image/upload/v1681673483/at_mine/Delta_yyi4v3.jpg",
      "https://res.cloudinary.com/duw4zfhmh/image/upload/v1681673483/at_mine/1200x630_garden_bbq_m24_full_m36_1025_sltv2u.jpg",
    ],
    category: "barbecue",
    price: 200,
    size: 30,
    address: "Carrer de les Granotes 10",
    city: "Barcelona",
    country: "Spain",
    zipCode: "08003",
    summary:
      "Enjoy the Mediterranean climate with this spacious outdoor area featuring a BBQ and seating for 8.",
    coordinates: { lat: 41.389505, lng: 2.187765 },
    amenities: ["wifi", "music", "tv", "kidFriendly"],
    active: true,
  },
  {
    title: "Barbecue & Garden",
    description:
      "Relax in this beautiful garden with a barbecue and seating for 6.",
    owner: "6437ef04d35e3202ffcb577e",
    images: [
      "https://res.cloudinary.com/duw4zfhmh/image/upload/v1681673543/at_mine/How-to-Design-the-Perfect-Outdoor-BBQ-Area-lighting_pjtqcx.jpg",
      "https://res.cloudinary.com/duw4zfhmh/image/upload/v1681673582/at_mine/5118ebf43e30830ec44bb0086bf69bdb_ibuk4u.jpg",
    ],
    category: "barbecue",
    price: 150,
    size: 25,
    address: "Carrer de l'Almirall Cervera 20",
    city: "Barcelona",
    country: "Spain",
    zipCode: "08003",
    summary:
      "Relax in this beautiful garden with a barbecue and seating for 6.",
    coordinates: { lat: 41.386766, lng: 2.187774 },
    amenities: ["wifi", "music", "tv", "kidFriendly"],
    active: true,
  },
  {
    title: "Beautiful garden in Gracia",
    description: "A beautiful garden space in the trendy Gracia neighbourhood.",
    owner: "64381929bac40f86d9008606",
    category: "garden",
    price: 80,
    size: 25,
    address: "Carrer de l'Alzina 1",
    city: "Barcelona",
    country: "Spain",
    zipCode: "08024",
    summary: "A beautiful garden space in the trendy Gracia neighbourhood.",
    coordinates: { lat: 41.406789, lng: 2.154186 },
    amenities: ["petFriendly", "kidFriendly"],
    images: [
      "https://res.cloudinary.com/duw4zfhmh/image/upload/v1681673137/at_mine/GardenDesignProject58_1_pcfqkv.jpg",
    ],
    active: true,
  },
  {
    title: "Rooftop garden in Eixample",
    description:
      "A cozy garden space on a rooftop in the Eixample neighbourhood.",
    owner: "64381929bac40f86d9008606",
    category: "garden",
    price: 100,
    size: 30,
    address: "Carrer d'Aribau 2",
    city: "Barcelona",
    country: "Spain",
    zipCode: "08011",
    summary: "A cozy garden space on a rooftop in the Eixample neighbourhood.",
    coordinates: { lat: 41.386925, lng: 2.15775 },
    amenities: ["music", "eventFriendly"],
    images: [
      "https://res.cloudinary.com/duw4zfhmh/image/upload/v1681673286/at_mine/Screenshot_2023-04-16_at_21.27.48_ob0s6v.png",
      "https://res.cloudinary.com/duw4zfhmh/image/upload/v1681673286/at_mine/Screenshot_2023-04-16_at_21.27.55_wvz0mp.png",
    ],
    active: true,
  },
  {
    title: "Private garden oasis in Sarria",
    description: "A peaceful garden space in the quiet Sarria neighbourhood.",
    owner: "643682134e3380f7d851a50f",
    category: "garden",
    price: 120,
    size: 35,
    address: "Carrer de Jaume Piquet 3",
    city: "Barcelona",
    country: "Spain",
    zipCode: "08017",
    summary: "A peaceful garden space in the quiet Sarria neighbourhood.",
    coordinates: { lat: 41.399078, lng: 2.122042 },
    amenities: ["kidFriendly", "petFriendly"],
    images: [
      "https://res.cloudinary.com/duw4zfhmh/image/upload/v1681673647/at_mine/Urban-Garden-Oasis-pv_v2z09d.jpg",
      "https://res.cloudinary.com/duw4zfhmh/image/upload/v1681673647/at_mine/Urban-Garden-Oasis-Patio-space-label_cvdeqa.jpg",
      "https://res.cloudinary.com/duw4zfhmh/image/upload/v1681673647/at_mine/greenwich-village-backyard-jeffrey-erb-img_24312aa1022c89f3_4-7392-1-f567740_aehkkh.jpg",
    ],
    active: true,
  },
  {
    title: "Spacious Photo Studio",
    description:
      "Large photo studio perfect for photoshoots and film productions.",
    owner: "64367e20c9b3919e623f083e",
    category: "photostudio",
    price: 200,
    size: 50,
    images: [
      "https://res.cloudinary.com/duw4zfhmh/image/upload/v1681673741/at_mine/mid_x3_dmgajg.jpg",
      "https://res.cloudinary.com/duw4zfhmh/image/upload/v1681673741/at_mine/image_processing20201113-1-vyz8ii_fnsj5d.jpg",
      "https://res.cloudinary.com/duw4zfhmh/image/upload/v1681673741/at_mine/mid_x3_1_qylxpw.jpg",
    ],
    address: "Carrer de Floridablanca 14",
    city: "Barcelona",
    country: "Spain",
    zipCode: "08015",
    summary: "Large photo studio perfect for photoshoots and film productions.",
    coordinates: { lat: 41.381387, lng: 2.153348 },
    amenities: ["wifi", "music", "tv", "heating", "kidFriendly"],
    active: true,
  },
  {
    title: "Top Photo Studio",
    description:
      "Bright and sunny photo studio for rent in the heart of the city.",
    owner: "643bbce594c0f104626df908",
    category: "photostudio",
    price: 150,
    size: 30,
    images: [
      "https://res.cloudinary.com/duw4zfhmh/image/upload/v1681673855/at_mine/stock-photo-100404647_tjkbqz.jpg",
      "https://res.cloudinary.com/duw4zfhmh/image/upload/v1681673741/at_mine/lg_1644082243331_iucbl7.jpg",
    ],
    address: "Carrer de Viladomat 52",
    city: "Barcelona",
    country: "Spain",
    zipCode: "08015",
    summary: "Bright and sunny photo studio for rent in the heart of the city.",
    coordinates: { lat: 41.38482, lng: 2.157085 },
    amenities: ["wifi", "music", "tv", "heating"],
    active: true,
  },
  {
    title: "Large Basement Space",
    description: "Spacious basement available for storage or workshop.",
    owner: "643bbce594c0f104626df908",
    images: [
      "https://res.cloudinary.com/duw4zfhmh/image/upload/v1681674220/at_mine/sports-fan-dream-basement-in-northern-virginia-metro-building-and-remodeling-group-llc-img_e9c1c0650c2cbcca_14-3247-1-2eb9578_floyu2.jpg",
      "https://res.cloudinary.com/duw4zfhmh/image/upload/v1681674220/at_mine/c76bd85e7a00e7d0c600b0e621bb2c97_qzbey0.jpg",
      "https://res.cloudinary.com/duw4zfhmh/image/upload/v1681674220/at_mine/aspen-french-house-plan-walker-home-design-img_2321d6770a626e42_14-8207-1-44e0988_wvb99s.jpg",
    ],
    category: "basement",
    price: 250,
    size: 50,
    address: "Carrer de València 14",
    city: "Barcelona",
    country: "Spain",
    zipCode: "08015",
    summary: "Spacious basement available for storage or workshop.",
    coordinates: { lat: 41.385812, lng: 2.157571 },
    amenities: ["wifi", "washer", "dryer"],
    active: true,
  },
  {
    title: "Basement Studio",
    description:
      "Beautifully designed basement studio ideal for artists or creatives.",
    owner: "643816e5bac40f86d90085bd",
    images: [
      "https://res.cloudinary.com/duw4zfhmh/image/upload/v1681674111/at_mine/recording-studio-kids-basement-cowdin-design-build-img_e031a7ee0acd1c0d_9-3389-1-1ee24aa_v971j4.jpg",
      "https://res.cloudinary.com/duw4zfhmh/image/upload/v1681674111/at_mine/recording-studio_uuku5r.jpg",
      "https://res.cloudinary.com/duw4zfhmh/image/upload/v1681674153/at_mine/e5e008aec0d490314e5a4b02672f30f4_ttmh76.jpg",
    ],
    category: "basement",
    price: 350,
    size: 80,
    address: "Carrer del Comte Borrell 42",
    city: "Barcelona",
    country: "Spain",
    zipCode: "08015",
    summary:
      "Beautifully designed basement studio ideal for artists or creatives.",
    coordinates: { lat: 41.385334, lng: 2.157667 },
    amenities: ["wifi", "music", "tv", "airConditioning", "heating"],
    active: true,
  },
  {
    title: "Spacious Event Venue",
    description: "A versatile event space for any occasion.",
    owner: "64367e20c9b3919e623f083e",
    category: "other",
    price: 500,
    size: 500,
    address: "Carrer de la Marina 1",
    city: "Barcelona",
    country: "Spain",
    zipCode: "08005",
    summary: "A versatile event space for any occasion.",
    coordinates: { lat: 41.394964, lng: 2.200094 },
    amenities: ["wifi", "music", "eventFriendly"],
    images: [
      "https://res.cloudinary.com/duw4zfhmh/image/upload/v1681674016/at_mine/tech_event_venue_barcelona_vfbjm3.jpg",
      "https://res.cloudinary.com/duw4zfhmh/image/upload/v1681674015/at_mine/41decdb59dfc1b553c1a4ab587f929b5-brooklynloft-events-001_pjlkvd.jpg",
    ],
    active: true,
  },
  {
    title: "Creative Co-working Space",
    description: "A bright and modern co-working space for creatives.",
    owner: "64367e20c9b3919e623f083e",
    category: "other",
    price: 200,
    size: 50,
    address: "Carrer de la Diputació 1",
    city: "Barcelona",
    country: "Spain",
    zipCode: "08015",
    summary: "A bright and modern co-working space for creatives.",
    coordinates: { lat: 41.38543, lng: 2.162044 },
    amenities: [
      "wifi",
      "music",
      "tv",
      "airConditioning",
      "heating",
      "kidFriendly",
    ],
    images: [
      "https://res.cloudinary.com/duw4zfhmh/image/upload/v1681673944/at_mine/creative-co-working-space-in-dubai-701-dubai-with-art-murals-in-business-bay-1280x853_jvzsje.jpg",
      "https://res.cloudinary.com/duw4zfhmh/image/upload/v1681673944/at_mine/X5NGnGzooL96BuJBcgnWtA_pik20y.jpg",
      "https://res.cloudinary.com/duw4zfhmh/image/upload/v1681673944/at_mine/396322_1_800_ukpqfi.jpg",
    ],
    active: true,
  },
];

mongoose
  .connect(process.env.MONGO_URL)
  .then((x) => console.log(`Connected to ${x.connection.name}`))
  .then(() => {
    return Property.deleteMany();
    // insert many properties
  })
  .then(() => {
    return Property.insertMany(propertiesToSeed);
  })
  .then(() => {
    console.log("Property seed done 🌱");
  })
  .catch((e) => console.log(e))
  .finally(() => {
    console.log("Closing connection");
    mongoose.connection.close();
  });

// Run npm run seed
